src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx
Fixed yaml indenting: yaml will now indent 2 spaces instead of one space
Additionally: Beautified resource template
=> Edanbranch

src/app/shared/components/utils.ts, src/app/shared/styles/elements/utils.scss, src/app/workflows/components/workflow-dag/workflow-dag.scss, src/models/workflows.ts
=> Clock for pending pods

src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx, src/app/workflows/components/workflows-list/workflows-list.tsx
Closes https://github.com/argoproj/argo/issues/977
=> Issue 977 - allow workflows to open in new tab

package.json, src/api/app.ts, src/api/utils.ts, src/app/shared/services/workflows-service.ts, yarn.lock
Closes https://github.com/argoproj/argo/issues/1018 .
PR depends on https://github.com/argoproj/argo/pull/1019
=> Issue #1018 - Try to read logs from s3 if pod is deleted

CONTRIBUTING.md, package.json, src/app/shared/components/index.ts, src/app/shared/components/nav-bar/nav-bar.scss, src/app/shared/components/nav-bar/nav-bar.tsx, src/app/shared/components/tooltip/tooltip.tsx, src/app/shared/components/top-bar/top-bar.scss, src/app/shared/components/top-bar/top-bar.tsx, src/app/shared/styles/elements/buttons.scss, src/app/shared/styles/elements/form-controls.scss, src/app/shared/styles/elements/utils.scss, stories/page.tsx, yarn.lock
https://github.com/argoproj/argo-cd/issues/1274
=> Ui enhancements

src/app/shared/components/layout/layout.tsx, src/app/shared/components/nav-bar/nav-bar.scss, src/app/shared/components/nav-bar/nav-bar.tsx
=> Enables version in nav-bar

package.json, src/app/shared/components/slide-contents/slide-contents.scss, src/app/shared/components/slide-contents/slide-contents.tsx, src/app/shared/components/utils.ts, src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.scss, src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx, src/models/workflows.ts, yarn.lock
I made a support of `WorkflowTemplate`. I changed the format of template YAML view so you can check the source of resolved templates.
I also updated node-sass version to ^4.12.0 because of https://github.com/sass/node-sass/issues/2632.
=> Support workflow template

src/components/popup/popup.tsx
Signed-off-by: Keith Chong <kykchong@redhat.com>
Remove unneeded quote.  This is continued from
https://github.com/argoproj/argo-ui/pull/74
which is the argo-ui part of the fix for argoproj/argo-cd#4844
=> fix: Design Flaw leading to errant delete - remove quote (#4844)

jest.config.js, package.json, src/components/data-loader.spec.tsx, src/components/data-loader.tsx, yarn.lock
https://github.com/argoproj/argo-cd/issues/4913
=> fix(data-loader): correctly support usage that excludes input entirely

yarn.lock
Signed-off-by: Daniel Herman <dherman@factset.com>
=> fix: upgrade all dependencies identified by snyk as having vulns

src/components/page/page.tsx
Signed-off-by: Daniel Herman <dherman@factset.com>
=> fix(page): correct typing errors

src/components/popup/popup-manager.spec.tsx, src/components/popup/popup-manager.tsx, src/components/popup/popup.tsx
- fix(popup): correct typing errors
- fix(popup-manager): correct typing errors
- test(popup-manager): add partial unit tests for popup manager
=> fix typing errors in a couple components

src/components/data-loader.tsx
=> fix: properly handle observable completion in data loader

src/components/layout/layout.tsx, src/components/nav-bar/nav-bar.scss, src/components/nav-bar/nav-bar.tsx, stories/page.tsx
https://user-images.githubusercontent.com/426437/105889850-7cae6f00-5fc3-11eb-807f-a4452ffe0fa8.mov
PR allows to programmatically enable compact and light style of nav bar using `<Layout navItems={navItems} navBarStyle={{light: true, compact: true}}>`
=> feat: support programmatically control nav bar style

package.json, src/components/dropdown/dropdown.tsx, src/components/popup/popup-manager.spec.tsx, src/components/select/select.tsx, src/components/ticker.tsx, src/components/utils.ts, src/tsconfig.json, stories/page.tsx, yarn.lock
=> refactor: upgrade rxjs

v2/components/theme-div/theme-div.stories.tsx, v2/yarn.lock
=> fix: update broken story book

v2/package.json, v2/yarn.lock
=> chore: Move rxjs and moment to peerDependencies

v2/utils/utils.tsx
=> fix: Error if callback was not passed to `useData`

v2/components/autocomplete/autocomplete.tsx
=> fix: Hide autocomplete suggestions on Enter but show on typing

v2/components/action-button/action-button.tsx, v2/components/autocomplete/autocomplete.tsx, v2/package.json, v2/shared/index.ts, v2/shared/keypress.tsx
=> fix: Insource react-keyhooks package

v2/shared/context/theme.tsx
=> fix: Fail gracefully when window and / or localstorage are undefined

src/components/tabs/tabs.tsx
Fixed endless re-rendering of Tabs component that was detected during investigation of https://github.com/argoproj/argo-cd/issues/7262
=> fix: Application details view performance issue #7262

src/components/navigation.ts
[NavigationManager]: fixed method that opens new tab when metaKey === true
=> fix: Cmd+Click on multiple applications opens each application in the same browser tab #7192

src/components/dropdown/dropdown.tsx, v2/components/autocomplete/autocomplete.tsx
Signed-off-by: ciiay <yicai@redhat.com>
Fixes issue #1524
=> fix: Nested Refresh dropdown does not work on Application Details page #1524

src/components/dropdown/dropdown.tsx, src/components/top-bar/top-bar.tsx
PR is required to support https://github.com/argoproj/argo-cd/pull/8176
=> feat: customizable page breadcrumbs

.github/workflows/build-v1.yml, src/components/top-bar/top-bar.tsx
PR fixes a bug introduced by https://github.com/argoproj/argo-ui/pull/175 that broken compilation. Additionally changes CI to run build for PRs
=> fix: change incorrect element key in Topbar component

package.json, src/components/logs-viewer/logs-viewer.scss, src/components/logs-viewer/logs-viewer.tsx, stories/index.stories.tsx, stories/logs-viewer.tsx, yarn.lock
PR upgrades xterm version and adapt LogsViewer to new xterm API
=> refactor: upgrade xterm version

.github/dependabot.yml, .github/workflows/dependabot-reviewer.yml
Signed-off-by: Alex Collins <alex_collins@intuit.com>
=> chore: Enabled dependabot

src/components/autocomplete/autocomplete-field.tsx, src/components/autocomplete/autocomplete.tsx, src/components/dropdown/dropdown.tsx, src/components/form-field/form-field.tsx, src/components/nav-bar/nav-bar.tsx, src/components/page/page.tsx, src/components/popup/popup.tsx, src/components/select/select.tsx, src/components/sliding-panel/sliding-panel.tsx, src/components/tabs/tabs.tsx, src/components/top-bar/top-bar.tsx, stories/table.tsx, yarn.lock
Signed-off-by: Alex Collins <alex_collins@intuit.com>
=> build: Upgrade to classnames@2.3.1

src/components/tooltip/tooltip.tsx
PR fixes broken tooltip component. Tooltip was broken after upgrading to latest tippy version.
=> fix: fix broken tooltip component

src/components/autocomplete/autocomplete.tsx
Fixes https://github.com/argoproj/argo-cd/issues/13067 
Signed-off-by: Keith Chong [kykchong@redhat.com]
=> fix: Revision drop down transparent, not visible to read (#13067)

.dockerignore, CONTRIBUTING.md
Remove unused & outdated files for less confusion
- `.dockerignore` is unused, there is no matching `Dockerfile`
- `CONTRIBUTING.md` is outdated
- there is no `yarn storybook` command currently
- the contributing docs are [in the README](https://github.com/argoproj/argo-ui/blob/c65a9520366b0c0cf0ac585618d029e60041a94d/README.md) as this is an internal argoproj library, not an app
=> chore: remove unused files

src/components/popup/popup-manager.tsx
Changes have been in my stash for a while are fairly noticeable
- remove extra whitespace in import 
- add lacking newlines in component JSX
Lint passes, pure whitespace change
While adding `prettier` et al could be useful, probably not worth given that this repo is deprecated per #453
=> style: fix whitespace issues in `popup-manager.tsx`
