Dockerfile
src/api/app.ts
src/api/main.ts

This PR resolves #6:
- Added API server parameter to set controller-instance value
- If `instanceId` is set, the `/api/workflows` endpoint will use additional label selector to limit the scope of listed workflows.

API server can filter workflows managed by specific workflow controller

---

src/app/shared/components/checkbox.tsx

So that it can be embedded in a `<p>` tag without the DOM validator complaining in the console.

Make checkbox a span instead of a div

---

src/app/help/components/help.tsx

This fixes the "Argo Project" link in the help screen. It previously directed to argoproj.io, which is down, so I changed it to the correct argoproj.github.io.

Fix argoproj link

---

src/app/workflows/components/workflow-details/workflow-details.scss

fixed 'X' not hiding under page when summary tab can scroll

---

Dockerfile
src/api/app.ts
src/api/main.ts

Argo is capable of operating in a single namespace. 
If you deploy argo-ui the same way (without clusterrole/clusterrolebindings just normal role/rolebindings) workflows cannot be accessed.
I created an extra environment configuration option "FORCE_NAMESPACE_ISOLATION" to allow this to function on the UI for a singlenamespace.
Hopefully this will help others to use argo-ui in a single namespace
With kind regards,
Dennis Rutjes

force namespace isolation

---

package.json
src/api/app.ts
yarn.lock

Adding express-winston turned out to be a pretty quick and easy way to add a bit more logging to the UI. I left the current error logging as is, but it might make sense to just remove it and use the error reporting that express-winston provides.

Add more logging

---

src/app/workflows/components/workflow-dag/workflow-dag.scss
src/app/workflows/components/workflow-dag/workflow-dag.tsx
src/app/workflows/components/workflow-details/workflow-details.scss

Hello!
While changing node size, I noticed that the values {x, y} returned by dagre are the center point of node/edge, as mentioned in [dagre wiki](https://github.com/dagrejs/dagre/wiki#output-graph):
> node, edge | x | For nodes, the x-coordinate for the center of the node. For edges the x-coordinate for the center of the edge label.
> 
> node, edge | y | For nodes, the y-coordinate for the center of the node. For edges the y-coordinate for the center of the edge label.
The code was using these values as top left point when positioning nodes. Some CSS translations and margins were added to correct those positioning, even though not necessary when top-left coordinates are properly calculated.
The translations were hard-coded to the currently used node width and height, making it …

Fix pointer usage: from top-left to middle

---

src/api/app.ts

Logs is not showing if workflow is in another namespace in argo-ui from v2.2.1

fix: fix get logs api, get namespace from parameters instead of query

---

Dockerfile
src/api/main.ts

I wanted to run argo-ui in local docker with host network and still make it able to get workflows from remote Kubernetes cluster by the following command.
```
docker run --net host -v ~/.kube:/root/.kube -p 8001:8001 --name argo-ui --rm argoproj/argoui:v2.2.1
```
In this case, since we're not sure if the port `8001` is available in the host, we should allow users to change binding IP and port.

Allow to set arbitrary bind ip and port

---

src/app/help/components/help.tsx

Currently, the help page's Documentation link is broken - this corrects the URI to the argo project page: arogproj.github.io

Correct help documentation URI to argoproj.github.io

---

src/components/navigation.ts

This enables to open application details from the application in a new browser tab, when CTRL was pressed on mouse click (just like browsers do with any other link).
Related to an issue reported in ArgoCD, https://github.com/argoproj/argo-cd/issues/3020

feat: Enable open application details in new tab on ctrl+click

---

src/components/popup/popup-manager.tsx
stories/popup.tsx

Signed-off-by: Keith Chong <kykchong@redhat.com>
In general, this is to allow any popup form content to have default values pre-set by clients.  See the storybook entry.  Here, the username field default value is set to `admin` and the checkbox is checked by default, when the popup appears.  See screenshot:
Specifically, this is needed by https://github.com/argoproj/argo-cd/issues/3205.  The confirmation dialog will be changed to a prompt, with confirmation to delete by requiring users to enter the application name.  That way, the Cascade checkbox can remain checked by default.
(Commit message has wrong issue.  It should be https://github.com/argoproj/argo-cd/issues/3205 and not 4844)

feat: Allow for default values to be set in popup forms (#3205)

---

src/components/popup/popup-manager.tsx

For https://github.com/argoproj/argo-cd/issues/4393 
The Delete Confirmation dialog was changed to a prompt dialog and the OK and Cancel buttons didn't already have locators.
Signed-off-by: Keith Chong <kykchong@redhat.com>

test: Add locators for Prompt OK and Cancel Buttons (#4393)

---

src/components/nav-bar/nav-bar.scss

With Argo Workflows UI v3, there are a lot of icons on the left - with the current size of the icons, they often don't all fit in the window, so this PR shrinks them slightly.
Additionally, I think simplifying the nav bar design a bit is a nice visual refresh and would give Workflows UI v3 an even clearer visual demarcation.

feat(ui): Update nav bar to better fit many icons and simplify design

---

src/components/data-loader.tsx

PR fixes data loader bug. Observable might complete without returning any data. In this case, data loader should not stuck

fix: support Observable that return no data

---

src/components/autocomplete/autocomplete.tsx

For argoproj/argo-cd#[5152](https://github.com/argoproj/argo-cd/issues/5152)
Autocomplete filter has been made case insensitive
Signed-off-by: Ishita Sequeira isequeir@redhat.com

fix: autocomplete filter to make it case insensitive #5152

---

src/components/data-loader.tsx

Another DataLoader bug fix: currently if data loader input changes before observable returns something it keep waiting forever. To reproduce:
* navigate to log viewer (e.g. https://cd.apps.argoproj.io/applications/argo-cd?node=%2FPod%2Fargocd%2Fargocd-redis-ha-haproxy-69c6df79c6-c9cfb%2F0&tab=logs) and enter a filter that does not match anything. 
* remove filter - loader keep waiting for results from previous request forewer

fix: data loader should return data if input has changed before observable returned first even

---

src/styles/elements/buttons.scss
src/styles/elements/form-controls.scss

This change would introduce visual cues when focus is applied to buttons and checkboxes.
Buttons when applied focus would behave the same way as when a user hovers over them and will also have a 1px teal border around them. (OK is focused below)
Checkboxes would have a 2px teal outline when focused.

fix: provide more visual cues for focused elements

---

.github/workflows/npm-publish.yml

chore: Don't run release action on push to release branch, rather manually from GitHub

---

v2/components/checkbox/checkbox.tsx

Fix: prevent crash when Checkbox onChange is null

---

v2/components/autocomplete/autocomplete.tsx

fix: prevent crash when autocomplete is fed array of nulls

---

v2/components/autocomplete/autocomplete.tsx

PR fixes minor visual glitch on safari:

fix: autocomplete items should be hidden using display: none

---

v2/components/autocomplete/autocomplete.tsx

PR https://github.com/argoproj/argo-ui/pull/123 fixed visual glitch in safari but introduced another bug: autocomplete unable to expand into right directory because hidden content has no height. PR fixes the glitch in another way.

fix: autocomplete should expand into right direction

---

v2/components/autocomplete/autocomplete.tsx

Abbreviation prop type changed to reuse resources Map<> in argo-cd as per comment on https://github.com/argoproj/argo-cd/pull/7466

fix: change prop type of abbreviations to Map

---

src/components/page/page.tsx
stories/page.tsx

Fixes https://github.com/argoproj/argo-ui/issues/164
Existing references to Page do not have to change. You'll have to add the new properties to take advantage of the change.
See above issue for screen shot.
Signed-off-by: Keith Chong <kykchong@redhat.com>

feat: Allow customized Page and TopBar titles (#164)

---

src/components/autocomplete/autocomplete.scss
src/components/autocomplete/autocomplete.tsx

Signed-off-by: ciiay yicai@redhat.com
Fixes: #7821
This PR is to remove bottom border on last item of a dropdown menu in Filter inputs.

fix: Trailing line in Filter Dropdown Menus #7821

---

src/components/layout/layout.tsx
src/components/nav-bar/nav-bar.tsx
stories/page.tsx

Signed-off-by: krrrr38 <k.kaizu38@gmail.com>
This feature allows to customize nav bar background color. It is required to https://github.com/argoproj/argo-workflows/pull/7387.
----
storybook

feat: customize nav bar background color style

---

src/styles/main.scss

Upstream Issue - https://github.com/argoproj/argo-cd/issues/9026. Currently argo-ui doesn't support regular(outlined icons).
The implementation upstream would look like this (let me know if this is better than the current behaviour) -  
Signed-off-by: saumeya <saumeyakatyal@gmail.com>

feat: add regular font awesome icons

---

src/components/autocomplete/autocomplete-field.tsx

Submitting as part of the fix for https://github.com/argoproj/argo-cd/issues/12798 
Reviewer(s) please double check that other places using AutocompleteField component are not negatively affected by this change. I checked the ones I found but I'm not 100% confident I didn't miss any.

fix for argocd issue 12798

---

package.json
yarn.lock

It seems like from the time when https://github.com/argoproj/argo-ui/pull/367 was initially created, a newer
version of react-toastify was released, which looks like it pulls in
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464, which is a pretty breaking
change. I haven't looked in depth, but I suspect if we were to upgrade
to the latest version we'd need to upgrade React...

fix: pin react-toastify

---

src/components/navigation.ts

signed-off-by: Yi Cai yicai@redhat.com
This is for argo-cd issue [#13362](https://github.com/argoproj/argo-cd/issues/13362): [UI] Middle mouse button click should open Application in new tab

Added mouse middle button click to app click event handler

---

src/components/popup/popup.scss

Fixes: https://github.com/argoproj/argo-workflows/issues/11448
**Before**:
**After**:

fix: add overflow to popup to make it scrollable

---

v2/components/tooltip/tooltip.stories.tsx
v2/components/tooltip/tooltip.tsx

includes the tooltip content inside the hover target, allowing users to hover the displayed values and copy/paste:
BEFORE
AFTER

[fix] make tooltip body persistent on hover

---

src/components/popup/popup.scss
src/components/select/select.scss
src/components/sliding-panel/sliding-panel.scss
src/components/tabs/tabs.scss
src/components/top-bar/top-bar.scss
src/styles/elements/containers.scss
src/styles/elements/form-controls.scss
src/styles/theme.scss

In this PR I've handled dark theme in the popup component and improved the colors of borders, text, and background that were too bright. 
Results in screenshots below. (it also needs some changes in Argo-CD repo)
Before
After
Before
After
Before
After
Before
After
Before
After

fix: dark mode improvements

---

package.json

- these are all inside of prod `dependencies` already (it has to be either or)
- notably, `antd` had a version mismatch between `dependencies` and `peerDependencies` (and it was a major version difference, v5 vs v4 after #387)
- `dependencies` supersede `peerDependencies` however, so the v5 dep was already used and the v4 dep was extraneous
- see the [`yarn.lock` file](https://github.com/argoproj/argo-ui/blob/c65a9520366b0c0cf0ac585618d029e60041a94d/yarn.lock#L5124) as evidence, as well as a downstream `yarn.lock`, such as [Argo Workflows's](https://github.com/argoproj/argo-workflows/blob/93914261cff4216561c89c1f5f6123e7ad0d5f61/ui/yarn.lock#L2812)
- note how this commit has no changes to the `yarn.lock` file either
- this mismatch did cause install warnings downstream as well, which were …

fix(deps): remove incorrectly duplicated peerDeps

---

README.md

The README is a bit dated -- particularly in its links to deps -- and could use some improvements
- Argo Rollouts also [uses this repo](https://github.com/argoproj/argo-rollouts/blob/db5e3b2a8ffd9aef8c1e2026985c906fc9eef068/ui/package.json#L11)
- update Yarn link to Yarn v1 / Classic, as those docs are quite different from the current v4 docs
- same for Storybook v6 vs current v7 / v8 beta
- say "Storybook" with an in-line link, not just a link. it is referred to as "Storybook"
- see also k8s style guide on [links](https://kubernetes.io/docs/contribute/style/style-guide/#links)
- <details> <summary>simplify "Build & Run" section a bit</summary>
- changing dirs to the repo you just cloned is implied. we don't say how to clone or fork, so leave this out too
- also you don't have to name …

docs: improve README with links and updates

---

.github/dependabot.yml

- use categorized labels, same as https://github.com/argoproj/argo-workflows/pull/12789
- follow our standard conventional commit prefixes for deps, same as https://github.com/argoproj/argo-workflows/pull/12881
- add `labels` and `commit-message` to `dependabot.yml`

ci(deps): set labels and commit prefix for dependabot

---

.github/workflows/stale.yml

- only run on issues labeled with "problem/more information needed"
- same as done in Workflows https://github.com/argoproj/argo-workflows/pull/12488
- most issues and PRs are marked and closed as stale in this repo only because they've never been followed up on, not because they're missing information
- for instance, a PR that never got a review or an issue with no maintainer response
- this has happened to me many times too and it even happens on pinned issues like #453
- and b/c of #453, this repo does not get much attention, which exacerbates the issue, resulting in closed PRs and issues that are actually still relevant 
- we should only start the stale process for issues/PRs that need action from the contributor, not ones that need action from maintainers
- same rationale as in …

ci: only run Stale Action on specifically labeled issues and PRs

---

package.json

- it was listed as `MIT` for some reason (copy+paste?), while Argo uses Apache, including this repo's own `LICENSE` file 
- also CNCF uses Apache
- fix `package.json:license` field

fix: `package.json:license` should be Apache

---

src/components/popup/popup.scss

Necessary for https://github.com/argoproj/argo-cd/pull/18116

feat(popup): styles for list element in popup

---

.github/workflows/stale.yml

- fix OpenSSF Scorecard issues
- have consistent settings here as in Workflows
- fix OpenSSF Scorecard issues
- set top-level `permissions` to read-only
- add comments for job-level `permissions`
- pin action to a SHA
- use same settings [as Workflows](https://github.com/argoproj/argo-workflows/blob/b4af68bdd48c41bcf75ba433357c9b9b01a0e0c1/.github/workflows/stale.yaml)
- with a dedicated `stale-issue-message` & `stale-pr-message`
- same cron `schedule`
- same formatting: indentionation and ordering etc
This will merge conflict with #549 (due to indentation etc changes), so it is a draft for now

refactor(ci): standardize Stale Action config

---

src/components/logs-viewer/logs-viewer.tsx

Fixes #557
Inspired from https://github.com/xtermjs/xterm.js/issues/2478#issuecomment-1002371588 this `attachCustomKeyEventHandler` on the terminal catch the `Ctrl+C` event, and if there is a current text selection, we force the browser to copy that text.

fix: copy logs text on Linux & Windows. Fixes #557

---

src/components/autocomplete/autocomplete.tsx

Follow-up to / Fixes https://github.com/argoproj/argo-ui/pull/560#discussion_r1631992541

fix(autocomplete): use JSDoc `@default` for `autoHighlight` prop

---

src/components/select/select.scss

fixes https://github.com/argoproj/argo-workflows/issues/7789
center align select arrow, fixes hidden arrow on no text selection
left(old) -> right(new)
argo-workflow:
argo-cd:

fix(select): vertically center arrow

---

package.json
src/components/duration.tsx
src/components/ticker.tsx
v2/utils/utils.tsx
yarn.lock

Related to the goals of https://github.com/argoproj/argo-workflows/issues/12059, just removing / replacing a large dep entirely.
Follow-up to https://github.com/argoproj/argo-workflows/pull/12097 and #534 here.
Needed for https://github.com/argoproj/argo-workflows/pull/12611
`moment` has been [deprecated since Sep 2020](https://momentjs.com/docs/#/-project-status/) and recommends using native `Intl` or newer libraries that make use of native `Intl`, such as `luxon` and `day.js`
- `moment` is also a very large dependency and hence is ripe for pruning and replacement as well
- remove `formatTimestamp` function from `v2/utils` as it is unused
- it is unused [internally](https://github.com/search?q=repo%3Aargoproj%2Fargo-ui+formattimestamp&type=code) (it is only exported here), unused by …

refactor(deps)!: remove `moment` dep and usage

---

src/components/utils.ts

Clean up unused code
- remove unused functions `getScrollParent` and `scrollTo` from `utils.ts`
- in this repo they are unused:
- https://github.com/search?q=repo%3Aargoproj%2Fargo-ui%20getScrollParent&type=code
- https://github.com/search?q=repo%3Aargoproj%2Fargo-ui+scrollTo&type=code
- in CD they are not used:
- https://github.com/search?q=repo%3Aargoproj%2Fargo-cd+getScrollParent&type=code
- https://github.com/search?q=repo%3Aargoproj%2Fargo-cd+scrollTo&type=code
- in Rollouts they are not used:
- https://github.com/search?q=repo%3Aargoproj%2Fargo-rollouts+getScrollParent&type=code
- https://github.com/search?q=repo%3Aargoproj%2Fargo-rollouts+scrollTo&type=code
- in Workflows they are not used:
- https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows+getScrollParent&type=code
- …

chore: remove unused Utils functions

---

src/context.tsx

- `components/` is not tree-shakeable, so importing it makes this file also not tree-shakeable
- similar to my PR downstream (https://github.com/argoproj/argo-workflows/pull/12158) and for the Storybook here (#567) to use individual imports
- Individually import `NotificationsApi` and `PopupApi` from their respective components instead of the non-treeshakeable components import
- also fixup some style in the order of imports and whitespace

refactor: make `context.tsx` tree-shakeable

---

src/components/duration.tsx

Follow-up to https://github.com/argoproj/argo-ui/pull/535#issuecomment-2151143975, fixes the issue I discovered in https://github.com/argoproj/argo-cd/pull/19655#issuecomment-2305897525
I previously left in `durationMs` for backward-compatibility so that you could use either, but I forgot to mark the types as optional, so both ended up being required by the typings, oops 🙃 
Instead of making them both confusingly optional (no way of doing "one of"), just remove the deprecated `durationMs` in another breaking change

fix!: remove deprecated `durationMs` prop

---

.github/workflows/build-v1.yml
package.json
yarn.lock

Equivalent to https://github.com/argoproj/argo-workflows/pull/11637 and PRs I've made in other repos
Same as downstream et al, see https://github.com/atlassian/yarn-deduplicate#why-is-this-necessary 
Removes ~2.5k+ LoC from the `yarn.lock` by consolidating duplicated deps (and saves on disk, installation, network, dep issues, etc)
In particular for this repo, all the dep removals and changes I've done for #569 #534 #567 etc have complicated `yarn.lock` diffs that I've manually reduced (sometimes a removal even causes an addition because `yarn` just adds the latest version of the dep). This does it automatically and will ensure it doesn't happen again.
I've wanted to do it for a while but it usually merge conflicts with any other dep changes so I kept deferring it and then forgetting it 😅 …

chore(deps): dedupe `yarn.lock`, add check for dupes
